// Code generated by defn gen. DO NOT EDIT.
package app

import (
	"github.com/defn/other/m/tenant/library/go/cmd/bootstrap"
	"github.com/defn/other/m/tenant/library/go/cmd/build"
	"github.com/defn/other/m/tenant/library/go/cmd/check"
	"github.com/defn/other/m/tenant/library/go/cmd/dispatch"
	"github.com/defn/other/m/tenant/library/go/cmd/gen"
	"github.com/defn/other/m/tenant/library/go/cmd/hatch"
	"github.com/defn/other/m/tenant/library/go/cmd/hello"
	"github.com/defn/other/m/tenant/library/go/cmd/lattice"
	"github.com/defn/other/m/tenant/library/go/cmd/pipeline"
	"github.com/defn/other/m/tenant/library/go/cmd/root"
	"github.com/defn/other/m/tenant/library/go/cmd/stamp"
	"github.com/defn/other/m/tenant/library/go/cmd/sync"
	"github.com/defn/other/m/tenant/library/go/cmd/version"
	"go.uber.org/fx"
)

// Modules aggregates all fx.Modules for the application.
var Modules = fx.Options(
	bootstrap.Module,
	build.Module,
	check.Module,
	dispatch.Module,
	gen.Module,
	hatch.Module,
	hello.Module,
	lattice.Module,
	pipeline.Module,
	root.Module,
	stamp.Module,
	sync.Module,
	version.Module,
)
