#!/usr/bin/env bbs
#MISE description= "Upgrade tool and module versions"


;; upgrade -- orchestrate version upgrades with subcommands.
;;
;; Usage:
;;   mise run upgrade mise              # upgrade mise tools, sync constrained versions
;;   mise run upgrade bzlmod            # upgrade Bazel module versions via BCR
;;   mise run upgrade go                # upgrade Go module dependencies
;;   mise run upgrade bzlmod mise go    # upgrade all (bzlmod first, then mise, then go)
;;
;; ## Subcommand: mise
;;
;; 1. Runs `mise upgrade --bump` to bump all mise-managed tools,
;;    excluding bzlmod-pinned tools (uv, python, node) whose versions
;;    are constrained by their Bazel modules
;; 2. Regenerates mise.toml from the (now-stale) versions.cue
;;    so that mise.toml reflects the bumped versions -- this is needed
;;    because `mise upgrade --bump` edits mise.toml directly
;; 3. Reads the bumped versions back from mise.toml and patches versions.cue
;;    to match (so CUE remains the source of truth)
;; 4. Runs sync-module-versions to clamp constrained tools (uv, python, node)
;;    back to the max version their Bazel modules support
;; 5. Runs `mise run gen` to regenerate all derived files
;; 6. Runs `mise install` to install any rolled-back versions
;;
;; ## Subcommand: go
;;
;; 1. Parses go.mod for direct dependencies (excludes indirect)
;; 2. Runs `go get -u` on each direct dependency individually so that
;;    transitive pseudo-version pins (e.g. k8s.io/api -> protobuf) don't
;;    collide with another direct's @upgrade target.
;; 3. Clamps k8s.io/* directs back down to whatever sigs.k8s.io/controller-runtime
;;    requires -- controller-runtime tags lag the k8s release cycle, so the
;;    independent @upgrade pass leaves k8s.io ahead of what controller-runtime
;;    can compile against.
;; 4. Runs `go mod tidy` to clean up go.sum (via hatch goupgrade)
;;
;; ## Subcommand: bzlmod
;;
;; 1. Queries the Bazel Central Registry (bcr.bazel.build) for the latest
;;    non-yanked, non-prerelease version of each Bazel module
;; 2. Updates versions.cue with the new module versions
;; 3. After bzlmod, you typically run `mise` subcommand too, because
;;    upgrading rules_uv/rules_python/rules_nodejs may change the
;;    constrained tool versions
;;
;; ## Version detection schemes (for agent maintenance)
;;
;; When a Bazel module changes its internal structure, the detection in
;; sync-module-versions.clj may break. Here's how each works:
;;
;; ### uv ← rules_uv
;; - File: uv/private/uv.lock.json (rules_multitool JSON lock)
;; - URL:  https://raw.githubusercontent.com/theoremlp/rules_uv/v{VER}/uv/private/uv.lock.json
;; - Parse: JSON → .uv.binaries[0].url → extract version from download URL
;;   e.g. ".../download/0.8.12/uv-aarch64-..." → "0.8.12"
;; - If rules_uv moves away from rules_multitool, this will break.
;;   Look for alternative version declarations in the repo.
;;
;; ### python ← rules_python
;; - File: python/versions.bzl (Starlark)
;; - URL:  https://raw.githubusercontent.com/bazelbuild/rules_python/{VER}/python/versions.bzl
;; - Parse: Regex for MINOR_MAPPING = { "3.14": "3.14.2", ... }
;;   Extracts stable (non-alpha/beta) patch versions, returns latest by semver.
;; - Fallback: If MINOR_MAPPING disappears, falls back to parsing
;;   TOOL_VERSIONS = { "3.14.2": { ... } } keys directly.
;; - Note: rules_python tags do NOT have a "v" prefix (just "1.9.0").
;;
;; ### node ← rules_nodejs
;; - File: nodejs/private/node_versions.bzl (Starlark, auto-generated)
;; - URL:  https://raw.githubusercontent.com/bazelbuild/rules_nodejs/v{VER}/nodejs/private/node_versions.bzl
;; - Parse: Regex for "{VERSION}-linux_arm64" entries.
;;   Filters to even-major (LTS) versions only, returns latest by semver.
;; - The file is generated by scripts/update-nodejs-versions.js and covers
;;   Node 8.x through 24.x. If rules_nodejs changes the dict format or
;;   moves the file, detection will break.
;;
;; ### crane ← rules_oci
;; - File: oci/private/versions.bzl (Starlark)
;; - URL:  https://raw.githubusercontent.com/bazel-contrib/rules_oci/v{VER}/oci/private/versions.bzl
;; - Parse: Regex for CRANE_VERSIONS = { "v0.18.0": { ... } } top-level keys.
;;   Returns the latest version key (with "v" prefix) by semver.
;; - If rules_oci changes the dict name or file location, detection will break.
;;
;; ### regctl ← rules_oci
;; - File: oci/private/versions.bzl (same file as crane)
;; - Parse: Regex for REGCTL_VERSIONS = { "v0.8.0": { ... } } top-level keys.
;;   Returns the latest version key (with "v" prefix) by semver.
;;
;; ### java ← rules_java
;; - File: java/repositories.bzl (Starlark)
;; - URL:  https://raw.githubusercontent.com/bazelbuild/rules_java/{VER}/java/repositories.bzl
;; - Parse: Regex for JDK version in Zulu download URLs:
;;   e.g. "zulu25.32.17-ca-jdk25.0.2-linux_x64.tar.gz" → "25.0.2"
;;   Returns "graalvm-community-{latest}" to match mise format.
;; - Note: rules_java tags do NOT have a "v" prefix (just "9.6.1").
;; - If rules_java changes to a different JDK vendor or URL pattern,
;;   detection will break. Look for alternative version declarations.
;;
;; ### helm ← helm/helm releases (latest GA)
;; - URL:  https://api.github.com/repos/helm/helm/releases/latest
;; - Parse: Regex for "tag_name": "vX.Y.Z" (strip leading v).
;; - Tracks latest helm release regardless of major version. History:
;;   this used to be pinned to whatever ArgoCD's hack/tool-versions.sh
;;   (helm3_version) shipped, because argocd-server embedded helm to
;;   render charts. Decoupled 2026-04-20 -- the platform renders via
;;   plain helm/kustomize now, so the argocd-pin is no longer relevant.
;;
;; ### kustomize ← kubernetes-sigs/kustomize releases
;; - URL:  https://api.github.com/repos/kubernetes-sigs/kustomize/releases
;; - Parse: Filter to "tag_name": "kustomize/vX.Y.Z"; pick highest semver.
;;   (The repo also tags api/v*, cmd/config/v*, kyaml/v*; we only want
;;   the kustomize/v* tags.)
;; - Same decoupling story as helm.
;;
;; ### k3s ← k3s v1.{minor} channel (minor from versions.cue)
;; - URL:  https://update.k3s.io/v1-release/channels/v1.{minor}
;; - Parse: Regex for vX.Y.Z in the redirect/response body.
;; - The minor family is anchored by the k3s version in versions.cue (not the
;;   upstream "stable" channel, which may lag behind). To move to a new k3s
;;   family (e.g. 1.36), update versions.cue k3s.version to any 1.36.x and
;;   sync-module-versions will pick up the latest 1.36 patch automatically.
;;
;; ### kubectl ← k3s
;; - kubectl version is set to match the k3s stable version directly.
;; - No external detection needed -- it mirrors whatever k3s resolves to.
;;
;; ### Bazel modules ← BCR
;; - URL:  https://bcr.bazel.build/modules/{NAME}/metadata.json
;; - Parse: JSON → .versions (list), .yanked_versions (map of version→reason)
;;   Filters out yanked versions and pre-release (contains "-rc", "-alpha", etc.).
;;   Returns the latest by semver-ish comparison.
;; - BCR metadata format is stable (part of the registry protocol).
;;   Unlikely to break unless a module is removed from BCR entirely.


(require '[defn :refer :all])


;; ---------------------------------------------------------------------------
;; Version helpers
;; ---------------------------------------------------------------------------

(defn parse-version-parts
  "Parse a version string into comparable parts.
   Strips non-numeric segments (like 'bcr') and returns a vector of integers.
   Handles semver (1.2.3), two-part (1.2), and BCR suffixes (34.0.bcr.1)."
  [v]
  (->> (str/split v #"\.")
       (filter #(re-matches #"\d+" %))
       (mapv parse-long)))


(defn version-compare
  "Compare two version strings. Pads shorter vectors with zeros so that
   length differences don't dominate (e.g. 7.1.0 > 6.0.0.1)."
  [a b]
  (let [pa  (parse-version-parts a)
        pb  (parse-version-parts b)
        len (max (count pa) (count pb))
        pad (fn [v] (into v (repeat (- len (count v)) 0)))]
    (compare (pad pa) (pad pb))))


(defn latest-version
  "Return the latest version from a collection."
  [versions]
  (last (sort version-compare versions)))


(defn prerelease?
  "True if the version looks like a pre-release (rc, alpha, beta, etc.)."
  [v]
  (boolean (re-find #"(?i)[-](rc|alpha|beta|dev|pre)" v)))


;; ---------------------------------------------------------------------------
;; BCR helpers
;; ---------------------------------------------------------------------------

(defn fetch-url
  "Fetch a URL, returning {:ok body} or {:err message}."
  [url]
  (try
    {:ok (slurp url)}
    (catch Exception e
      {:err (str "fetch failed: " (.getMessage e))})))


(defn bcr-latest-version
  "Query BCR for the latest non-yanked, non-prerelease version of a module."
  [module-name]
  (let [url    (str "https://bcr.bazel.build/modules/" module-name "/metadata.json")
        result (fetch-url url)]
    (if-let [body (:ok result)]
      (let [data     (parse-json body)
            versions (get data "versions")
            yanked   (set (keys (get data "yanked_versions")))
            usable   (->> versions
                          (remove yanked)
                          (remove prerelease?))]
        (if (seq usable)
          {:ok (latest-version usable)}
          {:err (str "cannot-be-determined: no usable versions for " module-name)}))
      {:err (str "cannot-be-determined: " (:err result))})))


;; ---------------------------------------------------------------------------
;; versions.cue patching (shared with sync-module-versions)
;; ---------------------------------------------------------------------------

(defn patch-cue-version
  "Replace the version string for a tool in versions.cue content.
   Anchored with tab to avoid partial name matches."
  [content tool-name new-version]
  (let [tool-pat (if (str/includes? tool-name "-")
                   (str "\"" (java.util.regex.Pattern/quote tool-name) "\"")
                   (java.util.regex.Pattern/quote tool-name))
        pattern  (re-pattern
                   (str "(\t" tool-pat ":\\s*#ToolVersion\\s*&\\s*\\{\\s*\n\\s*version:\\s*\")[^\"]*(\")"))
        replaced (str/replace content pattern (str "$1" new-version "$2"))]
    replaced))


;; ---------------------------------------------------------------------------
;; Subcommand: bzlmod
;; ---------------------------------------------------------------------------

;; Bazel module names are derived from MODULE.bazel at runtime: every
;; `bazel_dep(name = "X", ...)` line is a candidate for upgrade. Module names
;; in MODULE.bazel match CUE keys in versions.cue 1:1 (both use underscores),
;; so no further translation is needed.
;;
;; History: this was a hand-maintained list, which silently rotted as
;; modules were added/removed -- e.g. `toolchains_protoc` was removed from
;; MODULE.bazel but lingered in the list, producing a phantom
;; "UPDATE: toolchains_protoc -> 0.6.1" each run that patched nothing.
(defn read-bazel-modules
  "Parse MODULE.bazel and return the list of bazel_dep names."
  []
  (let [content (slurp "MODULE.bazel")
        pat     #"(?m)^bazel_dep\(\s*name\s*=\s*\"([^\"]+)\""]
    (->> (re-seq pat content)
         (map second)
         distinct
         vec)))


(defn upgrade-bzlmod!
  "Query BCR for latest versions of all Bazel modules and patch versions.cue."
  []
  (println "=== upgrade bzlmod ===")
  (println)

  (let [versions-json (run-tool-quiet "cue" "eval" "-e" "versions" "--out" "json"
                                      "./kernel/schema")
        versions      (parse-json versions-json)
        cue-path      "kernel/schema/versions.cue"
        original      (slurp cue-path)
        changed       (atom false)
        bazel-modules (read-bazel-modules)]

    ;; Query all modules in parallel (babashka pmap)
    (let [results (pmap (fn [mod-name]
                          (let [current (get-in versions [mod-name "version"])
                                latest  (bcr-latest-version mod-name)]
                            {:module  mod-name
                             :current current
                             :latest  latest}))
                        bazel-modules)]

      ;; Print results
      (doseq [{:keys [module current latest]} (sort-by :module results)]
        (if-let [v (:ok latest)]
          (if (= v current)
            (log-ok (str module " " current))
            (println (str "  UPDATE: " module " " current " → " v)))
          (println (str "  " module " " current " " (:err latest)))))

      (println)

      ;; Sanity check: every module pulled from MODULE.bazel must have a
      ;; corresponding entry in versions.cue. A module in MODULE.bazel but
      ;; not in versions.cue means gen would not propagate the bump anywhere
      ;; (and patch-cue-version would silently no-op).
      (let [missing (->> results
                         (filter #(:ok (:latest %)))
                         (remove #(get versions (:module %)))
                         (map :module))]
        (when (seq missing)
          (log-err (str "BUG: bazel_dep(s) " (str/join ", " missing)
                        " present in MODULE.bazel but missing from versions.cue"))
          (exit 1)))

      ;; Patch versions.cue
      (let [patched (reduce
                      (fn [content {:keys [module current latest]}]
                        (if-let [v (:ok latest)]
                          (if (= v current)
                            content
                            (do
                              (reset! changed true)
                              (patch-cue-version content module v)))
                          content))
                      original
                      results)]
        (if @changed
          (do
            (spit cue-path patched)
            (sh! "chmod" "644" cue-path)
            (log-ok "updated schema/versions.cue with new module versions")
            (println)
            (log-ok "hatching bzlmod upgrade to equilibrium...")
            (defn-bin! "hatch" "bzlmodupgrade"))
          (log-ok "all Bazel modules are at latest versions"))))))


;; ---------------------------------------------------------------------------
;; Subcommand: mise
;; ---------------------------------------------------------------------------

(defn read-mise-toml-versions
  "Parse the mise [tools] section and return {tool-name version-string}.
   Handles both simple (tool = \"ver\") and complex (tool = { version = \"ver\" }) forms.
   Reads root/.config/mise/config.toml -- the global mise config, symlinked from
   ~/.config/mise/config.toml -- since m/mise.toml has no [tools] section."
  []
  (let [lines   (str/split-lines (slurp "root/.config/mise/config.toml"))
        in-tools (atom false)
        result   (atom {})]
    (doseq [line lines]
      (cond
        (re-matches #"\[tools\]" line)
        (reset! in-tools true)

        (and @in-tools (re-matches #"\[.+\]" line))
        (reset! in-tools false)

        (and @in-tools (not (str/starts-with? (str/trim line) "#"))
             (not (str/blank? line)))
        (when-let [m (or
                       ;; Complex: tool = { version = "ver", ... }
                       (re-matches #"\"?([^\"\s=]+)\"?\s*=\s*\{\s*version\s*=\s*\"([^\"]+)\".*" line)
                       ;; Simple: tool = "ver"
                       (re-matches #"\"?([^\"\s=]+)\"?\s*=\s*\"([^\"]+)\"" line))]
          (swap! result assoc (nth m 1) (nth m 2)))))
    @result))


;; Mapping from mise tool IDs to CUE keys in versions.cue, derived by parsing
;; kernel/schema/mise.cue. Each entry in root_mise_tools pairs an `id: "X"`
;; with a `version: versions.Y.version` (or `versions["Y"].version`); we read
;; those pairs out as the source of truth.
;;
;; History: this used to be a hand-maintained table, which silently dropped
;; any tool whose mise ID didn't have an explicit mapping (e.g. river,
;; buildkite_cli, pitchfork). The drop fell out as "no version changes from
;; mise upgrade", and gen then regenerated config.toml from the stale
;; versions.cue, masking the bump entirely.
(defn build-mise-id->cue-key
  "Parse kernel/schema/mise.cue and return {mise-id cue-key}."
  []
  (let [content (slurp "kernel/schema/mise.cue")
        ;; Match `id: "X" ... version: versions.Y.version`
        ;; or    `id: "X" ... version: versions["Y"].version`
        ;; (?s) = dotall so .*? crosses newlines within a single block.
        pat     #"(?s)id:\s*\"([^\"]+)\".*?version:\s*versions(?:\.([a-zA-Z_][a-zA-Z0-9_]*)|\[\"([^\"]+)\"\])\.version"]
    (->> (re-seq pat content)
         (map (fn [[_ mise-id dot-key bracket-key]]
                [mise-id (or dot-key bracket-key)]))
         (into {}))))


(def mise-id->cue-key (delay (build-mise-id->cue-key)))


(defn resolve-cue-key
  "Map a mise tool ID to its CUE key in versions.cue.
   Returns the mapped key, or the original ID if no mapping exists."
  [tool-id]
  (get @mise-id->cue-key tool-id tool-id))


(defn upgrade-mise!
  "Run mise upgrade --bump, then sync constrained versions back."
  []
  (println "=== upgrade mise ===")
  (println)

  ;; Step 1: bump all mise tools (excluding bzlmod-constrained and special-handling ones)
  ;; uv, python, node, java, crane, regctl versions are pinned to what their
  ;; Bazel modules support.  Upgrading them here would just get rolled back
  ;; by sync-module-versions.
  ;; tailscale requires special handling (chart + image mirror coordination).
  ;; pnpm must sync with package.json packageManager field (otherwise pnpm
  ;; reinstalls endlessly); bump it manually in schema/versions.cue +
  ;; package.json together, then run `mise run gen`.
  (log-ok "running mise upgrade --bump (excluding bzlmod-pinned: uv, python, node, java, crane, regctl; special: tailscale, pnpm)")
  (sh!! "mise" "upgrade" "--bump"
        "--exclude" "uv" "--exclude" "python" "--exclude" "node"
        "--exclude" "java"
        "--exclude" "github:google/go-containerregistry"
        "--exclude" "github:regclient/regclient"
        "--exclude" "aqua:tailscale/tailscale"
        "--exclude" "pnpm")
  (println)

  ;; Step 2: read bumped versions from mise.toml back into versions.cue
  ;; mise upgrade --bump edits mise.toml directly, but versions.cue is our
  ;; source of truth. We need to propagate the bumped versions back.
  (log-ok "reading bumped versions from mise.toml")
  (let [bumped-versions (read-mise-toml-versions)
        cue-path        "kernel/schema/versions.cue"
        original        (slurp cue-path)
        versions-json   (run-tool-quiet "cue" "eval" "-e" "versions" "--out" "json"
                                        "./kernel/schema")
        cue-versions    (parse-json versions-json)
        changed         (atom false)]

    (let [patched (reduce
                    (fn [content [tool-id bumped-ver]]
                      (let [cue-key (resolve-cue-key tool-id)]
                        (if (get cue-versions cue-key)
                          (let [current (get-in cue-versions [cue-key "version"])]
                            (if (= bumped-ver current)
                              content
                              (do
                                (println (str "  " cue-key " " current " → " bumped-ver))
                                (reset! changed true)
                                (patch-cue-version content cue-key bumped-ver))))
                          ;; Tool exists in mise.toml but not in versions.cue.
                          ;; If kernel/schema/mise.cue lists it, the cue-key
                          ;; mapping is broken; if not, the tool is managed
                          ;; outside CUE -- skip with a warning.
                          (let [from-schema? (contains? @mise-id->cue-key tool-id)]
                            (if from-schema?
                              (do
                                (log-err (str "BUG: tool " tool-id " maps to cue-key " cue-key
                                              " but versions." cue-key " is not present in versions.cue"))
                                (exit 1))
                              (do
                                (log-ok (str "skipping " tool-id " (not in kernel/schema/mise.cue)"))
                                content))))))
                    original
                    bumped-versions)]
      (when @changed
        (spit cue-path patched)
        (sh! "chmod" "644" cue-path)
        (log-ok "updated schema/versions.cue with bumped versions"))
      (when-not @changed
        (log-ok "no version changes from mise upgrade"))))

  (println)

  ;; Step 3: sync constrained tool versions back to module-supported values
  (log-ok "syncing constrained tool versions to module-supported values")
  (sh!! ".mise/tasks/sync-module-versions.clj")
  (println)

  ;; Step 4: hatch to equilibrium and validate
  (log-ok "hatching mise upgrade to equilibrium...")
  (defn-bin! "hatch")
  (println)
  (log-ok "validating...")
  (sh!! "mise" "run" "gen")
  (println)
  (log-ok "mise upgrade complete"))


;; ---------------------------------------------------------------------------
;; Subcommand: go
;; ---------------------------------------------------------------------------

(defn- direct-version
  "Return the version string for a direct require in go.mod, or nil if not present
   as a direct dep. Matches '\\t<path> v<version>' lines outside the indirect set."
  [mod-content path]
  (let [pat (re-pattern (str "(?m)^\\t" (java.util.regex.Pattern/quote path) "\\s+(v\\S+)\\s*$"))]
    (when-let [m (re-find pat mod-content)]
      (second m))))


(defn- parse-cr-k8s-pins
  "Parse sigs.k8s.io/controller-runtime's go.mod from GOMODCACHE and return a
   map of {k8s.io/<name> version} for every k8s.io/* require it lists (direct
   or indirect). The pseudo-version of kube-openapi is included."
  [cr-version]
  (let [gomodcache (sh! "go" "env" "GOMODCACHE")
        cr-mod    (str gomodcache "/sigs.k8s.io/controller-runtime@" cr-version "/go.mod")]
    (when (fs/exists? cr-mod)
      (->> (slurp cr-mod)
           (re-seq #"(?m)^\s*(k8s\.io/[^\s]+)\s+(v\S+)")
           (map (fn [[_ p v]] [p v]))
           (into {})))))


(defn- pseudo-version?
  "True if v is a Go pseudo-version (vX.Y.Z-...YYYYMMDDHHMMSS-<12-hex>).
   Pseudo-versions are timestamp-ordered branch snapshots, not tagged releases."
  [v]
  (boolean (re-find #"\d{14}-[0-9a-f]{12}$" v)))


(defn clamp-k8s-to-controller-runtime!
  "If sigs.k8s.io/controller-runtime is a direct dep, downgrade any k8s.io/*
   directs that now exceed the versions controller-runtime requires. No-op
   when controller-runtime is not a direct dep, or when its pins already match.

   Skips pseudo-version pins (e.g. kube-openapi, k8s.io/utils): those are
   timestamp-ordered continuous-branch snapshots, not breaking semver releases,
   so MVS picks the higher one safely. Clamping them would actively undo every
   `go get -u` bump of those modules."
  []
  (let [mod-content (slurp "go.mod")
        cr-version  (direct-version mod-content "sigs.k8s.io/controller-runtime")]
    (when cr-version
      (let [cr-pins (parse-cr-k8s-pins cr-version)
            ;; Only clamp k8s.io/* that we list as a direct dep.
            pins    (->> cr-pins
                         (filter (fn [[p _]] (direct-version mod-content p)))
                         (filter (fn [[p v]] (not= v (direct-version mod-content p))))
                         (remove (fn [[_ v]] (pseudo-version? v))))]
        (when (seq pins)
          (log-ok (str "clamping k8s.io/* to controller-runtime " cr-version " pins"))
          (apply sh!! "go" "get"
                 (for [[p v] pins] (str p "@" v)))
          (println))))))


(defn upgrade-go!
  "Upgrade Go module dependencies."
  []
  (println "=== upgrade go ===")
  (println)

  ;; Step 1: upgrade all direct dependencies listed in go.mod
  ;;
  ;; Run `go get -u` per-package rather than passing the whole list at once.
  ;; A combined `go get -u a b c` makes every listed module's @upgrade target
  ;; a hard constraint, so when one direct (e.g. k8s.io/api) transitively
  ;; pins a pseudo-version of another listed direct (e.g. protobuf) that is
  ;; newer than that direct's latest tag, Go errors out instead of letting
  ;; MVS pick the higher version. Per-package upgrades let each transitive
  ;; bump flow through naturally.
  ;;
  ;; Note: `-u` is intentionally aggressive about transitive deps. Some
  ;; tooling-only transitives (e.g. counterfeiter, pulled in by
  ;; controller-idioms's tests) get bumped here and dropped by `go mod tidy`
  ;; in step 3, so you'll see "go: upgraded X v.. => v.." for X that never
  ;; sticks. We tried `go get <pkg>@latest` (no -u) to silence that, but it
  ;; caused MVS to thrash through pre-release versions (e.g. v0.36.0-alpha.2)
  ;; on the way to a stable resolution -- worse noise. Keep `-u` and live
  ;; with the cosmetic re-bump.
  (log-ok "upgrading Go module dependencies")
  (let [mod-content (slurp "go.mod")
        ;; Extract direct (non-indirect) require paths
        directs (->> (re-seq #"(?m)^\t([^\s]+)\s+v[^\s]+\s*$" mod-content)
                     (map second))]
    (doseq [pkg directs]
      (sh!! "go" "get" "-u" pkg)))
  (println)

  ;; Step 2: clamp k8s.io/* to versions the upgraded controller-runtime supports.
  ;;
  ;; sigs.k8s.io/controller-runtime tags lag the k8s.io release cycle: a
  ;; freshly tagged k8s.io v0.N.0 is typically incompatible with the latest
  ;; controller-runtime, which still requires v0.(N-1).x and uses APIs (e.g.
  ;; ResourceEventHandlerRegistration) the new k8s.io has changed. Step 1
  ;; pushes everything to its individual @upgrade head, leaving k8s.io ahead
  ;; of controller-runtime's pinned set. Re-pin k8s.io/* directs to the
  ;; versions controller-runtime requires so the build remains consistent.
  (clamp-k8s-to-controller-runtime!)

  ;; Step 3: hatch to equilibrium (tidy + gen + validate)
  (log-ok "hatching go upgrade to equilibrium...")
  (defn-bin! "hatch" "goupgrade")
  (println)

  (log-ok "go upgrade complete"))


;; ---------------------------------------------------------------------------
;; Subcommand: app (helm chart upgrades)
;; ---------------------------------------------------------------------------

;; Exceptions for app name -> CUE schema key mapping.
;; Default rule: replace "-" with "_".
(def app-cue-key-overrides
  {"linkerd-control-plane" "linkerd"
   "tailscale-operator"    "tailscale"})


(defn app->cue-key
  "Map a catalog app name to its CUE schema key in versions.cue."
  [app-name]
  (or (app-cue-key-overrides app-name)
      (str/replace app-name "-" "_")))


(defn strip-v
  "Remove leading 'v' prefix from a version string."
  [s]
  (if (and s (str/starts-with? s "v"))
    (subs s 1)
    s))


(defn patch-cue-tool-field
  "Replace a field's quoted value within a tool's #ToolVersion block.
   Anchored to the tool header so it cannot cross block boundaries."
  [content tool-name field-name new-value]
  (let [tool-pat (if (str/includes? tool-name "-")
                   (str "\"" (java.util.regex.Pattern/quote tool-name) "\"")
                   (java.util.regex.Pattern/quote tool-name))
        field-pat (java.util.regex.Pattern/quote field-name)
        pattern  (re-pattern
                   (str "(\t" tool-pat ":\\s*#ToolVersion\\s*&\\s*\\{[^}]*?"
                        field-pat ":\\s+\")[^\"]*(\")"))
        replaced (str/replace content pattern (str "$1" new-value "$2"))]
    replaced))


(defn helm-show-chart
  "Run helm show chart, return {:chart-version :app-version} or nil."
  [chart-name chart-repo]
  (try
    (let [oci?      (str/starts-with? chart-repo "oci://")
          chart-ref (if oci? (str chart-repo "/" chart-name) chart-name)
          args      (if oci?
                      ["helm" "show" "chart" chart-ref]
                      ["helm" "show" "chart" chart-ref "--repo" chart-repo])
          output    (str/trim (:out (apply sh!!? args)))]
      (when-not (str/blank? output)
        (let [cv (second (re-find #"(?m)^version:\s*(.+)" output))
              av (second (re-find #"(?m)^appVersion:\s*(.+)" output))]
          (when cv
            {:chart-version (str/trim cv)
             :app-version   (str/trim (or av ""))}))))
    (catch Exception _ nil)))


(defn discover-app-updates
  "Query all catalog apps for available chart upgrades.
   Returns seq of maps with :app-name, :cue-key, :chart-name, :chart-repo,
   :current-chart-ver, :current-app-ver, :latest-chart-ver, :latest-app-ver,
   :upgrade?"
  []
  ;; Helm-app instances live in the library tenant after the kernel/tenant
  ;; decoupling (kernel/catalog/apps.cue is schema-only). Only library carries
  ;; charts -- defn-tenant apps are all `raw` (no chart_name/chart_repo) and
  ;; would be filtered out anyway.
  (let [apps-json    (run-tool-quiet "cue" "export" "-e" "apps" "--out" "json"
                                     "./tenant/library/catalog")
        apps         (parse-json apps-json)
        versions-json (run-tool-quiet "cue" "export" "-e" "versions" "--out" "json"
                                      "./kernel/schema")
        versions     (parse-json versions-json)]
    (->> apps
         (pmap (fn [[app-name app-info]]
                 (let [chart-name (get app-info "chart_name")
                       chart-repo (get app-info "chart_repo")
                       app-path   (get app-info "path")]
                   (when (and chart-name chart-repo)
                     (let [cue-key     (app->cue-key app-name)
                           current-cv  (get-in versions [cue-key "chart_version"])
                           current-av  (get-in versions [cue-key "version"])
                           latest      (helm-show-chart chart-name chart-repo)]
                       (when latest
                         (let [lcv (:chart-version latest)
                               lav (:app-version latest)]
                           {:app-name          app-name
                            :app-path          app-path
                            :cue-key           cue-key
                            :chart-name        chart-name
                            :chart-repo        chart-repo
                            :current-chart-ver current-cv
                            :current-app-ver   current-av
                            :latest-chart-ver  (strip-v lcv)
                            :latest-app-ver    (strip-v lav)
                            :upgrade?          (and (not= (strip-v lcv) current-cv)
                                                    (not (prerelease? lcv)))})))))))
         (remove nil?)
         (sort-by :app-name))))


(defn extract-images
  "Extract all container image references from a rendered manifest file."
  [gen-app-path]
  (when (fs/exists? gen-app-path)
    (->> (str/split-lines (slurp (str gen-app-path)))
         (keep #(second (re-find #"image:\s+\"([^\"]+)\"" %)))
         set)))


(defn pre-validate-chart
  "Dry-run kustomize build with the new chart to catch template errors
   (e.g. missing required values) before committing to the upgrade.
   Returns nil on success, error string on failure."
  [app-path chart-tgz chart-name new-chart-ver]
  (let [tmp (str (create-temp-dir {:prefix "validate-"}))]
    (try
      ;; Copy kustomization.yaml with updated chart version
      (copy-file (str app-path "/kustomization.yaml") (str tmp "/kustomization.yaml"))
      (let [kust (slurp (str tmp "/kustomization.yaml"))
            name-pat (java.util.regex.Pattern/quote chart-name)
            kust (str/replace kust
                              (re-pattern (str "(?m)(name:\\s*" name-pat "\\s*\n\\s*version:\\s*)[^\n]+"))
                              (str "$1" new-chart-ver))]
        (spit (str tmp "/kustomization.yaml") kust))
      ;; Extract chart into charts/ subdir
      (fs/create-dirs (str tmp "/charts"))
      (sh! "tar" "xzf" (str chart-tgz) "-C" (str tmp "/charts"))
      ;; Run kustomize build
      (let [result (sh!!? "kustomize" "build" "--enable-helm" tmp)]
        (if (zero? (:exit result))
          nil
          (str/trim (:err result))))
      (finally
        (delete-tree tmp)))))


(defn download-chart!
  "Download a chart to tmp-dir. Returns path to the .tgz or throws."
  [chart-name chart-repo chart-ver tmp-dir]
  (let [oci?      (str/starts-with? chart-repo "oci://")
        chart-ref (if oci? (str chart-repo "/" chart-name) chart-name)
        pull-args (if oci?
                    ["helm" "pull" chart-ref "--version" chart-ver "-d" tmp-dir]
                    ["helm" "pull" chart-ref "--repo" chart-repo
                     "--version" chart-ver "-d" tmp-dir])]
    (apply sh!! pull-args)
    (first (fs/glob tmp-dir "*.tgz"))))


(defn apply-chart-update!
  "Download new chart, validate, update versions.cue, kustomization.yaml,
   swap tarballs. Returns result map with :status (:ok or :skipped),
   :old-manifest, :new-manifest, :old-images."
  [{:keys [app-name app-path cue-key chart-name chart-repo
           current-chart-ver current-app-ver
           latest-chart-ver latest-app-ver]}]
  (let [kust-path (str app-path "/kustomization.yaml")
        tmp-dir  (str (create-temp-dir {:prefix "upgrade-app-"}))]

    ;; 1. Save old manifest and extract old images for later comparison
    (let [old-manifest (str app-path "/gen-app.cue")
          old-images   (extract-images old-manifest)]
      (when (fs/exists? old-manifest)
        (copy-file old-manifest (str tmp-dir "/gen-app-old.cue")))

      ;; 2. Download new chart
      (let [new-tgz (download-chart! chart-name chart-repo latest-chart-ver tmp-dir)]

        ;; 3. Pre-validate: dry-run kustomize build with new chart
        (let [err (pre-validate-chart app-path (str new-tgz) chart-name latest-chart-ver)]
          (when err
            (log-err (str app-name ": template validation failed -- skipping"))
            (log-err (str "  " (first (str/split-lines err))))
            (println (str "  Fix: add required values to " kust-path " then re-run"))
            (println)
            ;; Return skipped status so caller knows not to include in gen
            (throw (ex-info "validation-failed"
                            {:status     :skipped
                             :app-name   app-name
                             :error      err}))))

        ;; 4. Compute SHA256
        (let [sha256   (first (str/split (sh! "sha256sum" (str new-tgz)) #"\s+"))
              tgz-name (str (fs/file-name new-tgz))]

          ;; 5. Update versions.cue
          (let [cue-path "kernel/schema/versions.cue"
                content  (-> (slurp cue-path)
                             (patch-cue-tool-field cue-key "chart_version" latest-chart-ver)
                             (patch-cue-tool-field cue-key "chart_sha256" sha256)
                             (patch-cue-tool-field cue-key "version" latest-app-ver))]
            (spit cue-path content)
            (sh! "chmod" "644" cue-path))

          ;; 6. Update kustomization.yaml -- chart version + image tags
          (when (fs/exists? kust-path)
            (let [kust     (slurp kust-path)
                  name-pat (java.util.regex.Pattern/quote chart-name)
                  kust     (str/replace kust
                                        (re-pattern (str "(?m)(name:\\s*" name-pat
                                                         "\\s*\n\\s*version:\\s*)"
                                                         (java.util.regex.Pattern/quote current-chart-ver)))
                                        (str "$1" latest-chart-ver))
                  old-bare (strip-v current-app-ver)
                  new-bare (strip-v latest-app-ver)
                  kust     (if (and (not= old-bare new-bare)
                                    (not (str/blank? old-bare)))
                             (-> kust
                                 (str/replace
                                   (re-pattern (str "(?m)(newTag:\\s+)v"
                                                    (java.util.regex.Pattern/quote old-bare)
                                                    "\\s*$"))
                                   (str "$1v" new-bare))
                                 (str/replace
                                   (re-pattern (str "(?m)(newTag:\\s+)"
                                                    (java.util.regex.Pattern/quote old-bare)
                                                    "\\s*$"))
                                   (str "$1" new-bare)))
                             kust)]
              (spit kust-path kust)))

          ;; 7. (mirrors.cue bump happens in `defn hatch helmupgrade` via
          ;;     stamp.BumpMirrorTagsFromKustomization -- it reads the newTag
          ;;     values just written in step 6 and rewrites each matching
          ;;     mirror_images entry atomically (source/tag/digest). The CUE
          ;;     key-parity invariant in catalog/mirrors.cue guards against
          ;;     partial updates.)

          ;; 8. Swap tarballs
          (doseq [old-tgz (fs/glob app-path "*.tgz")]
            (fs/delete old-tgz))
          (copy-file (str new-tgz) (str app-path "/" tgz-name))))

      {:status      :ok
       :app-name    app-name
       :old-manifest (str tmp-dir "/gen-app-old.cue")
       :new-manifest (str app-path "/gen-app.cue")
       :old-images  old-images})))


(defn show-manifest-diff
  "Show deduplicated diff between old and new rendered manifests."
  [{:keys [app-name old-manifest new-manifest]}]
  (when (fs/exists? old-manifest)
    (let [result (sh!!? "diff" old-manifest new-manifest)]
      (if (zero? (:exit result))
        (log-ok (str app-name ": no manifest changes"))
        (let [out-lines  (str/split-lines (:out result))
              changed    (filter #(re-matches #"^[<>].*" %) out-lines)
              unique     (sort (set changed))]
          (println)
          (println (str "--- " app-name " (" (count changed) " changed lines) ---"))
          (doseq [line (take 30 unique)]
            (println (str "  " line)))
          (when (> (count unique) 30)
            (println (str "  ... and " (- (count unique) 30) " more"))))))))


(defn upgrade-app!
  "Discover and apply helm chart upgrades.
   With no args: dry-run showing available upgrades.
   With app names: upgrade those apps.
   With --all: upgrade everything available."
  [args]
  (println "=== upgrade app ===")
  (println)

  (log-ok "discovering available chart upgrades...")
  (println)

  (let [updates    (discover-app-updates)
        upgrade-all (some #{"--all"} args)
        app-filter  (when-not upgrade-all
                      (set (remove #(str/starts-with? % "-") args)))]

    ;; Show discovery results
    (doseq [{:keys [app-name current-chart-ver latest-chart-ver
                    current-app-ver latest-app-ver upgrade?]} updates]
      (let [selected (or upgrade-all
                         (and (seq app-filter) (app-filter app-name)))]
        (cond
          (not upgrade?)
          (log-ok (str app-name " " current-chart-ver
                       " (app " current-app-ver ") -- up to date"))

          (and upgrade? (not selected))
          (println (str "  AVAILABLE: " app-name " "
                        current-chart-ver " -> " latest-chart-ver
                        " (app " current-app-ver " -> " latest-app-ver ")"))

          :else
          (println (str "  UPGRADE:   " app-name " "
                        current-chart-ver " -> " latest-chart-ver
                        " (app " current-app-ver " -> " latest-app-ver ")")))))

    (println)

    ;; If dry-run (no args), stop here
    (when (empty? args)
      (log-ok "dry run -- pass app names or --all to upgrade")
      (exit 0))

    ;; Filter to apps that need upgrading and are selected
    (let [to-upgrade (filter (fn [{:keys [app-name upgrade?]}]
                               (and upgrade?
                                    (or upgrade-all
                                        (app-filter app-name))))
                             updates)]

      (when (empty? to-upgrade)
        (log-ok "nothing to upgrade")
        (exit 0))

      ;; Apply upgrades (with pre-validation)
      (log-ok (str "upgrading " (count to-upgrade) " chart(s)..."))
      (println)

      (let [results (reduce (fn [acc info]
                              (log-ok (str (:app-name info) ": downloading "
                                           (:chart-name info) " "
                                           (:latest-chart-ver info)))
                              (try
                                (conj acc (apply-chart-update! info))
                                (catch clojure.lang.ExceptionInfo e
                                  (if (= :skipped (:status (ex-data e)))
                                    acc
                                    (throw e)))))
                            [] to-upgrade)
            applied (filter #(= :ok (:status %)) results)]

        (when (empty? applied)
          (log-ok "no charts passed validation -- nothing to rebuild")
          (exit 0))

        ;; Hatch each upgraded app to equilibrium: gen + build + sync,
        ;; detect image source changes, fix app.cue + mirrors.cue,
        ;; re-hatch if needed, then validate with full pipeline.
        (println)
        (doseq [{:keys [app-name]} applied]
          (defn-bin! "hatch" "helmupgrade" app-name))
        (println)

        ;; Show diffs
        (log-ok "manifest changes:")
        (doseq [r applied]
          (show-manifest-diff r))

        (println)
        (log-ok (str "upgraded " (count applied) " chart(s). Review changes, then commit."))))))


;; ---------------------------------------------------------------------------
;; Main: dispatch subcommands
;; ---------------------------------------------------------------------------

(let [cmds (vec *command-line-args*)]
  (when (empty? cmds)
    (println "Usage: mise run upgrade <subcommand>...")
    (println)
    (println "Subcommands:")
    (println "  all                  Upgrade everything (go, bzlmod, mise)")
    (println "  app                  List available helm chart upgrades (dry run)")
    (println "  app NAME [NAME...]   Upgrade specific app charts")
    (println "  app --all            Upgrade all app charts")
    (println "  bzlmod               Upgrade Bazel module versions from BCR")
    (println "  go                   Upgrade Go module dependencies")
    (println "  mise                 Upgrade mise tools, sync constrained versions")
    (println)
    (println "Examples:")
    (println "  mise run upgrade all")
    (println "  mise run upgrade app")
    (println "  mise run upgrade app argocd traefik")
    (println "  mise run upgrade app -- --all")
    (println "  mise run upgrade mise")
    (println "  mise run upgrade bzlmod")
    (println "  mise run upgrade go")
    (exit 1))

  (if (= (first cmds) "app")
    (upgrade-app! (rest cmds))
    (doseq [cmd cmds]
      (case cmd
        "all"    (do (upgrade-go!) (println)
                     (upgrade-bzlmod!) (println)
                     (upgrade-mise!))
        "bzlmod" (upgrade-bzlmod!)
        "go"     (upgrade-go!)
        "mise"   (upgrade-mise!)
        (do
          (log-err (str "unknown subcommand: " cmd))
          (exit 1)))
      (println))))
