"""Macro for k3d cluster directories."""

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//kernel:fmt.bzl", "fmt_test")
load("//kernel:tagged.bzl", "tagged_file")
load("//kernel/gen-versions:cue.bzl", "CUE_VERSION")

def k3d_cluster(name, k3s_version, cluster_name, api_port, workspace_path, has_bootstrap = False, has_irsa = False, aws_profile = "", aws_region = ""):
    """Generate k3d cluster config files and register them with Bazel.

    Args:
        name: Bazel target name prefix.
        k3s_version: k3s version string.
        cluster_name: k3d cluster name.
        api_port: kubeAPI host port.
        workspace_path: path relative to workspace root (e.g. "k3d" or "k3d/a").
        has_bootstrap: whether this cluster has ArgoCD bootstrap.yaml.
        has_irsa: whether tofu has produced the per-cluster irsa.cue (set
                  True after the first `tofu apply` and commit irsa.cue;
                  unset on cluster teardown).
        aws_profile: AWS SSO profile name for tofu/aws commands.
        aws_region: AWS region for tofu/aws commands.
    """

    # k3d.yaml
    native.genrule(
        name = name + "_yaml_gen",
        srcs = ["//kernel/interface/k3d:templates.cue"],
        outs = ["k3d_gen.yaml"],
        cmd = "{ echo '# Generated by Bazel from k3d.cue -- DO NOT EDIT.' && echo '# Run: mise run gen' && echo && mise x cue@" + CUE_VERSION + " -- cue export -e config --out yaml" +
              " -t k3s_version=" + k3s_version +
              " -t cluster_name=" + cluster_name +
              " -t api_port=" + api_port +
              " $(location //kernel/interface/k3d:templates.cue); } > $@",
    )

    sh_binary(
        name = name + "_yaml_sync",
        srcs = ["//gen/.mise/tasks:gen-sync.clj"],
        args = [
            workspace_path + "/k3d.yaml",
            "$(location :" + name + "_yaml_gen)",
        ],
        data = [
            ":" + name + "_yaml_gen",
            "//kernel/lib:defn.clj",
        ],
        env = {"BBS_LIB": "$(rootpath //kernel/lib:defn.clj)"},
    )

    sh_test(
        name = name + "_yaml_drift_test",
        timeout = "short",
        srcs = ["//gen/.mise/tasks:gen-drift.clj"],
        args = [
            "$(location k3d.yaml)",
            "$(location :" + name + "_yaml_gen)",
        ],
        data = [
            "k3d.yaml",
            ":" + name + "_yaml_gen",
            "//kernel/lib:defn.clj",
        ],
        env = {"BBS_LIB": "$(rootpath //kernel/lib:defn.clj)"},
        tags = ["drift"],
    )

    # mise.toml
    native.genrule(
        name = name + "_mise_toml_gen",
        srcs = ["//kernel/interface/k3d:templates.cue"],
        outs = ["mise_gen.toml"],
        cmd = "mise x cue@" + CUE_VERSION + " -- cue export -e mise_toml --out text" +
              " -t k3s_version=" + k3s_version +
              " -t cluster_name=" + cluster_name +
              " -t api_port=" + api_port +
              " -t aws_profile=" + aws_profile +
              " -t aws_region=" + aws_region +
              " $(location //kernel/interface/k3d:templates.cue) > $@",
    )

    sh_binary(
        name = name + "_mise_toml_sync",
        srcs = ["//gen/.mise/tasks:gen-sync.clj"],
        args = [
            workspace_path + "/mise.toml",
            "$(location :" + name + "_mise_toml_gen)",
        ],
        data = [
            ":" + name + "_mise_toml_gen",
            "//kernel/lib:defn.clj",
        ],
        env = {"BBS_LIB": "$(rootpath //kernel/lib:defn.clj)"},
    )

    sh_test(
        name = name + "_mise_toml_drift_test",
        timeout = "short",
        srcs = ["//gen/.mise/tasks:gen-drift.clj"],
        args = [
            "$(location mise.toml)",
            "$(location :" + name + "_mise_toml_gen)",
        ],
        data = [
            "mise.toml",
            ":" + name + "_mise_toml_gen",
            "//kernel/lib:defn.clj",
        ],
        env = {"BBS_LIB": "$(rootpath //kernel/lib:defn.clj)"},
        tags = ["drift"],
    )

    # .kube/.gitignore
    native.genrule(
        name = name + "_kube_gitignore_gen",
        srcs = ["//kernel/interface/k3d:templates.cue"],
        outs = ["kube_gitignore_gen"],
        cmd = "mise x cue@" + CUE_VERSION + " -- cue export -e kube_gitignore --out text" +
              " -t k3s_version=" + k3s_version +
              " -t cluster_name=" + cluster_name +
              " -t api_port=" + api_port +
              " $(location //kernel/interface/k3d:templates.cue) > $@",
    )

    sh_binary(
        name = name + "_kube_gitignore_sync",
        srcs = ["//gen/.mise/tasks:gen-sync.clj"],
        args = [
            workspace_path + "/.kube/.gitignore",
            "$(location :" + name + "_kube_gitignore_gen)",
        ],
        data = [
            ":" + name + "_kube_gitignore_gen",
            "//kernel/lib:defn.clj",
        ],
        env = {"BBS_LIB": "$(rootpath //kernel/lib:defn.clj)"},
    )

    sh_test(
        name = name + "_kube_gitignore_drift_test",
        timeout = "short",
        srcs = ["//gen/.mise/tasks:gen-drift.clj"],
        args = [
            "$(location .kube/.gitignore)",
            "$(location :" + name + "_kube_gitignore_gen)",
        ],
        data = [
            ".kube/.gitignore",
            ":" + name + "_kube_gitignore_gen",
            "//kernel/lib:defn.clj",
        ],
        env = {"BBS_LIB": "$(rootpath //kernel/lib:defn.clj)"},
        tags = ["drift"],
    )

    # Format checks
    fmt_test(
        name = name + "_yaml_fmt",
        src = "k3d.yaml",
        tool = "yq",
    )

    fmt_test(
        name = name + "_mise_toml_fmt",
        src = "mise.toml",
        tool = "taplo",
    )

    fmt_test(
        name = name + "_kube_gitignore_fmt",
        src = ".kube/.gitignore",
        tool = "textfmt",
    )

    # File type tags
    tagged_file(
        name = name + "_yaml_tag",
        src = "k3d.yaml",
        tags = ["cue", "generated"],
    )

    tagged_file(
        name = name + "_mise_toml_tag",
        src = "mise.toml",
        tags = ["config", "generated", "mise", "toml"],
    )

    tagged_file(
        name = name + "_kube_gitignore_tag",
        src = ".kube/.gitignore",
        tags = ["config", "generated", "git"],
    )

    # Cluster context for CUE unification with apps
    fmt_test(
        name = name + "_cluster_cue_fmt",
        src = "cluster.cue",
        tool = "cue",
    )

    tagged_file(
        name = name + "_cluster_cue_tag",
        src = "cluster.cue",
        tags = ["cue", "generated"],
    )

    fmt_test(
        name = name + "_gitignore_fmt",
        src = ".gitignore",
        tool = "textfmt",
    )

    tagged_file(
        name = name + "_gitignore_tag",
        src = ".gitignore",
        tags = ["config", "generated", "git"],
    )

    # IRSA tofu config
    fmt_test(
        name = name + "_main_tf_fmt",
        src = "main.tf",
        tool = "tofu",
    )

    tagged_file(
        name = name + "_main_tf_tag",
        src = "main.tf",
        tags = ["config", "generated"],
    )

    # ArgoCD apps.yaml
    fmt_test(
        name = name + "_apps_yaml_fmt",
        src = "apps.yaml",
        tool = "yq",
    )

    tagged_file(
        name = name + "_apps_yaml_tag",
        src = "apps.yaml",
        tags = ["generated"],
    )

    # Bootstrap (ArgoCD install manifests, only for hub clusters)
    if has_bootstrap:
        fmt_test(
            name = name + "_bootstrap_yaml_fmt",
            src = "bootstrap.yaml",
            tool = "binary",
        )

        tagged_file(
            name = name + "_bootstrap_yaml_tag",
            src = "bootstrap.yaml",
            tags = ["generated"],
        )

    # IRSA values from tofu (only present after `tofu apply` produces irsa.cue
    # and the operator commits it). Tracking irsa.cue is what makes
    # `mise run check` deterministic across workstations -- otherwise the
    # gen pipeline would read whichever workstation's local tofu state
    # exists at gen time. See AIDR-00124 / AIDR-00125 for the design.
    if has_irsa:
        fmt_test(
            name = name + "_irsa_cue_fmt",
            src = "irsa.cue",
            tool = "cue",
        )

        tagged_file(
            name = name + "_irsa_cue_tag",
            src = "irsa.cue",
            tags = ["cue", "generated"],
        )
