# auto-generated by defn gen from catalog/aws.cue aws_allowed_regions.
# DO NOT EDIT -- edit catalog/aws.cue and run `mise run gen`.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.40.0"
      configuration_aliases = [
      ]
    }
  }
}
