# auto-generated by defn gen
terraform {
  required_providers {
    aws = {
      version = "6.40.0"
      source  = "aws"
    }
  }
  backend "s3" {
    bucket         = ""
    use_lockfile   = true
    use_path_style = true
    encrypt        = true
    key            = "stacks/global/terraform.tfstate"
    profile        = "other-org"
    region         = ""
  }

}

