# Generated by `defn gen` (seed phase) -- do not hand-edit.
# Tenant filegroup labels consumed by kernel/spec/BUILD.bazel
# tests; AIDR-00138 D5.3 -- kernel BUILD has no hardcoded tenants.

TENANT_CATALOG_FILES_LABELS = [
    "//tenant/library/catalog:catalog_files",
    "//tenant/other/catalog:catalog_files",
]

TENANT_AUTH_CUE_LABELS = [
    "//tenant/other/catalog:auth.cue",
]

TENANT_SPEC_FILES_LABELS = [
    "//tenant/library/spec:spec_files",
    "//tenant/other/spec:spec_files",
]
