@experiment(aliasv2,explicitopen,shortcircuit,try)

// templates.cue -- OCI brick BUILD.bazel generation.

import "github.com/defn/other/kernel/helpers"

_name: string @tag(name)

build_bazel: _header + "\n\n" + helpers.FmtLoads + "\n\n" + helpers.BuildBazelFmt + "\n\n" + helpers.BuildBazelTag + "\n\n" + helpers.DispatchCueRules

_header: #"""
	"""OCI external image '\#(_name)' -- generated by defn gen."""
	"""#
