@experiment(aliasv2,explicitopen,shortcircuit,try)

// Manual allow-list shard stamped by `defn bootstrap init` for the
// fork's namesake CLI seed (AIDR-00141 Stage 3.5d). main.go + app/
// wiring are hand-editable seeds; modules.go is regenerated by gocmd.

package contracts

_manualFileShards: cli: [
	"tenant/other/spec/manual-files-cli.cue",
	"tenant/other/go/cmd/other/BUILD.bazel",
	"tenant/other/go/cmd/other/dispatch.cue",
	"tenant/other/go/cmd/other/main.go",
	"tenant/other/go/cmd/other/app/BUILD.bazel",
	"tenant/other/go/cmd/other/app/app.go",
	"tenant/other/go/cmd/other/app/dispatch.cue",
	"tenant/other/go/cmd/other/app/modules.go",
	"bin/other",
]
