@experiment(aliasv2,explicitopen,shortcircuit,try)

// Manual allow-list shard: go/ -- Go source files outside generators.
//
// One of multiple manual-files-*.cue shards per AIDR-00083; sharded
// to enable parallel-write safety when bricks claim hand-written
// files concurrently. See contracts-schema.cue for the
// _manualFileShards aggregation pattern.

package contracts

_manualFileShards: go: [
	"kernel/spec/manual-files-go.cue",
	"tenant/other/go/cmd/other/BUILD.bazel",
	"tenant/other/go/cmd/other/dispatch.cue",
	"tenant/library/go/cmd/hello/schema.cue",
	"tenant/library/go/cmd/root/BUILD.bazel",
	"tenant/library/go/cmd/root/root.go",
	"tenant/other/go/cmd/other/integration_test.go",
	"tenant/other/go/cmd/other/app/BUILD.bazel",
	"tenant/other/go/cmd/other/app/app.go",
	"tenant/other/go/cmd/other/app/dispatch.cue",
	"tenant/other/go/cmd/other/app/modules.go",
	"tenant/defn/go/lib/bot/ingest/BUILD.bazel",
	"tenant/library/go/lib/spec/BUILD.bazel",
	"tenant/library/go/lib/spec/spec.go",
	"tenant/library/go/lib/spec/spec_test.go",
	"tenant/other/go/cmd/other/main.go",
	"tenant/other/go/cmd/other/testdata/stamp_brick_basic.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_brick_dashed_names.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_brick_errors.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_brick_idempotent_stamp_type.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_brick_parent.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_brick_stamp_type.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_brick_update.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_appends.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_basic.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_errors.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_generator.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_idempotent.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_schema.txtar",
	"tenant/other/go/cmd/other/testdata/stamp_midas_stamp_type.txtar",
	"tenant/other/go/cmd/other/testdata/version.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/01_empty.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/02_single_brick.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/03_disjoint_writes.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/04_simple_collision.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/05_multi_path_same_pair.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/06_ancestor_pair_skipped.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/07_ancestor_skipped_either_direction.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/08_multi_pair_collisions.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/09_three_way_collision.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/10_mixed_ancestor_and_sibling.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/11_path_prefix_match_not_strict_ancestor.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/12_partial_overlap_disjoint_remainder.txtar",
	"tenant/library/go/lib/spec/brickcollision/testdata/13_duplicate_path_within_brick.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/01_empty.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/02_single_brick.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/03_disjoint_writes.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/04_brick_a_reads_brick_b_writes.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/05_brick_a_writes_brick_b_reads.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/06_transitive_three_bricks.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/07_glob_matches_concrete_write.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/08_glob_matches_nothing.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/09_multiple_intersections_same_pair.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/10_self_loop_skipped.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/11_ancestor_pair_skipped.txtar",
	"tenant/library/go/lib/spec/brickreads/testdata/12_determinism.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/01_empty.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/02_single_leaf.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/03_two_leafs_clean.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/04_profile_hardcode_violation.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/05_path_hardcode_violation.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/06_bare_name_violation.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/07_library_reference_allowed.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/08_generator_output_skipped.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/09_comment_skipped.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/10_catalog_borrow_allowed.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/11_self_reference_allowed.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/12_multiple_violations_sorted.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/13_toml_single_quoted_violation.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/14_backtick_raw_violation.txtar",
	"tenant/library/go/lib/spec/crosstenantlit/testdata/15_bazel_extension_in_scope.txtar",
]
