@experiment(aliasv2,explicitopen,shortcircuit,try)

package deps

deps: [
	"//v/buildkite--agent/api",
	"//v/buildkite--agent/api/proto/gen",
	"//v/buildkite--agent/core",
	"//v/buildkite--agent/env",
	"//v/buildkite--agent/internal/agenthttp",
	"//v/buildkite--agent/internal/awslib",
	"//v/buildkite--agent/internal/experiments",
	"//v/buildkite--agent/internal/job",
	"//v/buildkite--agent/internal/job/hook",
	"//v/buildkite--agent/internal/ptr",
	"//v/buildkite--agent/internal/shell",
	"//v/buildkite--agent/kubernetes",
	"//v/buildkite--agent/logger",
	"//v/buildkite--agent/metrics",
	"//v/buildkite--agent/process",
	"//v/buildkite--agent/status",
	"@com_connectrpc_connect//:connect",
	"@com_github_aws_aws_sdk_go_v2//aws",
	"@com_github_aws_aws_sdk_go_v2_config//:config",
	"@com_github_aws_aws_sdk_go_v2_feature_ec2_imds//:imds",
	"@com_github_aws_aws_sdk_go_v2_service_ec2//:ec2",
	"@com_github_aws_aws_sdk_go_v2_service_ec2//types",
	"@com_github_brunoscheufler_aws_ecs_metadata_go//:aws-ecs-metadata-go",
	"@com_github_buildkite_go_pipeline//:go-pipeline",
	"@com_github_buildkite_go_pipeline//signature",
	"@com_github_buildkite_roko//:roko",
	"@com_github_buildkite_shellwords//:shellwords",
	"@com_github_denisbrodbeck_machineid//:machineid",
	"@com_github_dustin_go_humanize//:go-humanize",
	"@com_github_gowebpki_jcs//:jcs",
	"@com_github_prometheus_client_golang//prometheus/promhttp",
	"@com_google_cloud_go_compute_metadata//:metadata",
	"@org_golang_google_api//compute/v1:compute",
	"@org_golang_google_api//option",
	"@org_golang_x_oauth2//google",
]
